// where: standalone/canister/build.rs
// what: Build the single-canister frontend and generate embedded asset definitions
// why: The canister ships its own caller UI, so the Wasm build must always know which static assets to embed

use std::env;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let standalone_root = manifest_dir.parent().expect("standalone root");
    let web_root = standalone_root.join("web");
    let dist_dir = web_root.join("dist");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let did_path = manifest_dir.join("iclaw_ic.did");

    println!(
        "cargo:rerun-if-changed={}",
        did_path.display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        web_root.join("package.json").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        web_root.join("package-lock.json").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        web_root.join("index.html").display()
    );
    println!("cargo:rerun-if-changed={}", web_root.join("src").display());
    println!(
        "cargo:rerun-if-changed={}",
        web_root.join("public").display()
    );

    ensure_frontend_build(&web_root);
    write_ui_asset_module(&dist_dir, &out_dir.join("ui_assets.rs"));
}

fn ensure_frontend_build(web_root: &Path) {
    run(
        Command::new("npm").arg("install").current_dir(web_root),
        "npm install failed for standalone/web",
    );
    run(
        Command::new("npm")
            .args(["run", "build"])
            .current_dir(web_root),
        "npm run build failed for standalone/web",
    );
}

fn run(command: &mut Command, message: &str) {
    let status = command.status().expect(message);
    if !status.success() {
        panic!("{message}");
    }
}

fn write_ui_asset_module(dist_dir: &Path, output_path: &Path) {
    let mut paths = collect_files(dist_dir);
    paths.sort();

    let mut body = String::from("// @generated by standalone/canister/build.rs\n");
    body.push_str("pub static UI_ASSETS: &[EmbeddedUiAsset] = &[\n");

    for asset_path in paths {
        let relative = asset_path
            .strip_prefix(dist_dir)
            .expect("asset under dist")
            .to_string_lossy()
            .replace('\\', "/");
        let content_type = content_type_for(&relative);
        let cache_control = if relative == "index.html" {
            "public, no-cache, no-store"
        } else {
            "public, max-age=31536000, immutable"
        };
        body.push_str(&format!(
            "    EmbeddedUiAsset {{ path: \"{relative}\", bytes: include_bytes!(r#\"{}\"#), content_type: \"{content_type}\", cache_control: \"{cache_control}\" }},\n",
            asset_path.display()
        ));
    }

    body.push_str("];\n");
    body.push_str("pub const UI_INDEX_PATH: &str = \"index.html\";\n");

    fs::write(output_path, body).expect("write ui assets");
}

fn collect_files(root: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    for entry in fs::read_dir(root).expect("read dist") {
        let entry = entry.expect("dist entry");
        let path = entry.path();
        if path.is_dir() {
            files.extend(collect_files(&path));
        } else if path.file_name() != Some(OsStr::new(".DS_Store")) {
            files.push(path);
        }
    }
    files
}

fn content_type_for(path: &str) -> &'static str {
    match path.rsplit('.').next().unwrap_or_default() {
        "html" => "text/html; charset=utf-8",
        "js" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "svg" => "image/svg+xml",
        "json" => "application/json",
        "ico" => "image/x-icon",
        "map" => "application/json",
        _ => "application/octet-stream",
    }
}
